### ISSUE TITLE
Display something if a game is currently in a no-hitter

### ISSUE THREAD

**Issue by ajbowler** [MLB-LED-Scoreboard/mlb-led-scoreboard#116]
The overview API from mlbgame returns a No-Hitter flag, it would be neat to display this baseball magic on the board.

**Comment by ajbowler** [comment]
Possibly move the outs below the bases, move the pitch count upwards, and display "NO H" below the pitch count.

**Comment by swemoney** [comment]
I like the idea of displaying this info if we do it dynamically after, say, the 6th inning (maybe the number of innings that need to pass before displaying no hitter can be configurable).

Playing with the coords, moving the bases up and putting the outs under DOES fit, but the bases intercepts the inning arrow in that case. Plus, we would be moving elements to completely different places contextually (unless you wanted to move the outs under the bases permanently, which I'm not sure I love).

The better looking answer, to me, is if we just slide the pitch count up to 20 and the outs down to 30 and print the NO H in the middle. This is less jarring when the NO H shows up because it just squeezes itself in the middle of those elements instead of moving things to completely different locations.

Also, with the current font (which I believe if the smallest one offered?), we only have room for 3 characters. I tried "N.H" and it doesn't look too bad.

Besides those concerns, it's trivially easy to add.

**Comment by swemoney** [comment]
I actually got antsy and threw it together real quick the way I described. The only thing that doesn't make it perfect is I couldn't come up with an elegant way of adding the coords to the json without requiring a lot more to be done to the relevant renderers. Check it out and let me know what you think.

I took [a couple of pictures](https://imgur.com/a/QV3UNs5) of what it looks like.

MLB-LED-Scoreboard/mlb-led-scoreboard/tree/nohitter

**Comment by ajbowler** [comment]
I like it! I think for N.H. (or P.G., the data also has a flag for if it's a perfect game), I would do the following:

Change the font color to something else - AtBat shows a red banner, I think since no-hitters and perfect games are so special, they should stand out more with a different color, maybe a bright red.

Also I would move the outs up by one pixel, it looks awkward having them touch the bottom edge.
