### ISSUE TITLE
Newbie Help Needed

### ISSUE THREAD

**Issue by positivitysports** [MLB-LED-Scoreboard/mlb-led-scoreboard#305]
Hello, I'm brand new to GitHub so bear with me.  I have a little bit of programming experience and learning this new.  I know what you're saying and I'm hoping to learn as much as I can.

First, what do I download to get into my system and eventually push out to the screen when it comes in?

Second, are there tutorials on how to set keyboard buttons to control items on the screen?  I'd like to be able to produce a real scoreboard using this method and be able to customize the score, keep track of time(s), etc. for different sports and activities my kids do.  Somehow, I'm blocked and think it's a simple thing I'm missing.  I have a hello-world and that's it for right now.  Any help will be positively appreciated.

**Comment by pawptart** [comment]
Hi, these questions may be more suited for the [Slack channel](https://mlb-led-scoreboard.herokuapp.com/) rather than a Github issue.

---

For installing the software, checkout the README for instructions on installation. Worth noting there is a known issue with `feedparser` right now, which you can resolve with the following: https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/issues/299#issuecomment-693529178. If you run into a 

```
feedparser requires Python '>=3.6' but the running Python is x.x.x
```

error while running the software, that workaround should fix it.

---

Finally, this project is fairly tightly coupled to data that MLB provides. It's not intended to be a general-purpose scoreboard of the type you're trying to create. You *theoretically* could rip out the rendering system from this project and refactor it to accept custom input, but it's likely to be a massive undertaking.

I would suggest looking at the LED matrix driver uses under the hood and design software that's custom built for what you need: https://github.com/hzeller/rpi-rgb-led-matrix

There is also a tutorial out there for a general purpose scoreboard: https://www.tomshardware.com/news/this-raspberry-pi-scoreboard-keeps-score-for-any-game (you could possibly re-engineer this to work with a LED matrix).
